# itk-version: 3.1.0
version: "3"

services:
  phpfpm:
    image: itkdev/php8.2-fpm:latest
    volumes:
      - ./freescout:/app
    networks:
      - frontend

  nginx:
    volumes:
      - ./freescout:/app

