services:
  phpfpm:
    image: itkdev/php8.2-fpm:latest
    environment:
      - PHP_POST_MAX_SIZE=22M
      - PHP_UPLOAD_MAX_FILESIZE=20M
      - PHP_SENDMAIL_PATH=/usr/bin/msmtp --host=mail --port=1025 --read-recipients
    volumes:
      - ./freescout:/app
      # See README.md for details on what's going on here
      - ./freescout-resources/views/modules/enduserportal/emails/login.blade.php:/app/resources/views/modules/enduserportal/emails/login.blade.php
      - ./freescout-resources/views/modules/enduserportal/login.blade.php:/app/resources/views/modules/enduserportal/login.blade.php
      - ./freescout-resources/views/modules/enduserportal/partials/submit_form.blade.php:/app/resources/views/modules/enduserportal/partials/submit_form.blade.php
    networks:
      - frontend

  nginx:
    environment:
      NGINX_MAX_BODY_SIZE: 25M
      NGINX_WEB_ROOT: /app/public
    volumes:
      - ./freescout:/app
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.rule=Host(`${COMPOSE_SUPPORT_DOMAIN}`)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.regex=${COMPOSE_SUPPORT_REGEX}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.replacement=http://${COMPOSE_DOMAIN}${COMPOSE_SUPPORT_URL}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.middlewares=${COMPOSE_PROJECT_NAME}-redirect-support"
  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'

  mail:
    environment:
        # https://mailpit.axllent.org/docs/configuration/runtime-options/
        - "MP_VERBOSE=true"
