services:
  phpfpm:
    image: itkdev/php8.2-fpm:alpine
    environment:
      - PHP_POST_MAX_SIZE=22M
      - PHP_UPLOAD_MAX_FILESIZE=20M
    volumes:
      - ./freescout:/app

  nginx:
    environment:
      NGINX_MAX_BODY_SIZE: 25M
      NGINX_WEB_ROOT: /app/public
      COMPOSE_SERVER_DOMAIN: ${COMPOSE_SERVER_DOMAIN}
      COMPOSE_SUPPORT_DOMAIN: ${COMPOSE_SUPPORT_DOMAIN}
    volumes:
      - ./freescout:/app
    labels:
      # Add cors header to allow JS.
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-cors.headers.accesscontrolalloworiginlist=https://${COMPOSE_SUPPORT_DOMAIN}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-cors.headers.accesscontrolallowheaders=Content-Type,Authorization"

      # Added CSP headers
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-strip-csp.headers.customResponseHeaders.Content-Security-Policy="
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-add-csp.headers.customResponseHeaders.Content-Security-Policy=default-src * 'unsafe-inline' 'unsafe-hashes' 'unsafe-eval' data:;"

      # Adding extra labels to add support domain.
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.rule=Host(`${COMPOSE_SUPPORT_DOMAIN}`)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.regex=${COMPOSE_SUPPORT_REGEX}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.replacement=https://${COMPOSE_SERVER_DOMAIN}${COMPOSE_SUPPORT_URL}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.middlewares=${COMPOSE_PROJECT_NAME}-redirect-support,${COMPOSE_PROJECT_NAME}-strip-csp,${COMPOSE_PROJECT_NAME}-add-csp,${COMPOSE_PROJECT_NAME}-cors"

  supervisor:
    image: itkdev/supervisor-php8.2:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=php /app/artisan queue:work --queue='${WORK_QUEUES}' --sleep=5 --tries=1 --timeout=1800
      - APP_SUPERVISOR_WORKERS=2
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./freescout:/app:delegated

  redis:
    image: 'redis:6'
    restart: unless-stopped
    networks:
      - app

  memcached:
    deploy:
      replicas: 0
