version: "3"

services:
  phpfpm:
    image: itkdev/php8.2-fpm:alpine
    volumes:
      - ./freescout:/app
    networks:
      - frontend

  nginx:
    volumes:
      - ./freescout:/app

  supervisor:
    image: itkdev/supervisor-php8.2:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=php /app/artisan queue:work --queue='${WORK_QUEUES}' --sleep=5 --tries=1 --timeout=1800
      - APP_SUPERVISOR_WORKERS=2
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./freescout:/app:delegated
