services:
  phpfpm:
    image: itkdev/php8.2-fpm:latest
    environment:
      - PHP_POST_MAX_SIZE=22M
      - PHP_UPLOAD_MAX_FILESIZE=20M
    volumes:
      - ./freescout:/app
    networks:
      - frontend

  nginx:
    environment:
      NGINX_MAX_BODY_SIZE: 25M
    volumes:
      - ./freescout:/app

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'