services:
  phpfpm:
    image: itkdev/php8.2-fpm:alpine
    environment:
      - PHP_POST_MAX_SIZE=22M
      - PHP_UPLOAD_MAX_FILESIZE=20M
    volumes:
      - ./freescout:/app

  nginx:
    environment:
      NGINX_MAX_BODY_SIZE: 25M
    volumes:
      - ./freescout:/app
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.rule=Host(`${COMPOSE_SUPPORT_DOMAIN}`)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.regex=${COMPOSE_SUPPORT_REGEX}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.replacement=https://${COMPOSE_SERVER_DOMAIN}${COMPOSE_SUPPORT_URL}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.middlewares=${COMPOSE_PROJECT_NAME}-redirect-support"

  supervisor:
    image: itkdev/supervisor-php8.2:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=php /app/artisan queue:work --queue='${WORK_QUEUES}' --sleep=5 --tries=1 --timeout=1800
      - APP_SUPERVISOR_WORKERS=2
      - APP_SUPERVISOR_USER=deploy
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./freescout:/app:delegated

  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'
