services:
  phpfpm:
    image: itkdev/php8.2-fpm:latest
    environment:
      - PHP_POST_MAX_SIZE=22M
      - PHP_UPLOAD_MAX_FILESIZE=20M
    volumes:
      - ./freescout:/app
    networks:
      - frontend

  nginx:
    environment:
      NGINX_MAX_BODY_SIZE: 25M
      NGINX_WEB_ROOT: /app/public 
    volumes:
      - ./freescout:/app
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.rule=Host(`${COMPOSE_SUPPORT_DOMAIN}`)"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.regex=${COMPOSE_SUPPORT_REGEX}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.replacement=http://${COMPOSE_DOMAIN}${COMPOSE_SUPPORT_URL}"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-redirect-support.redirectregex.permanent=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-support.middlewares=${COMPOSE_PROJECT_NAME}-redirect-support"
  redis:
    image: 'redis:6'
    networks:
      - app
    ports:
      - '6379'
