version: '3'

dotenv: [".task.env", ".env", ".env.local"]

vars:
  TARGET_DIR: 'freescout'
  PLUGIN_TARGET_DIR: 'freescout/Modules'
  DOCKER_COMPOSE: '{{ .TASK_DOCKER_COMPOSE | default "itkdev-docker-compose-server" }}'

tasks:
  dist:build:
    summary: Install Freescout distribution
    cmds:
      - sh -c "wget https://github.com/freescout-help-desk/freescout/archive/refs/tags/{{.FREESCOUT_VERSION}}.tar.gz"
      - sh -c "mkdir freescout"
      - sh -c "tar -xzf ./{{.FREESCOUT_VERSION}}.tar.gz --strip-components 1 -C freescout"
      - sh -c "rm {{.FREESCOUT_VERSION}}.tar.gz"

  start-docker:
    cmds:
      - sh -c "{{ .DOCKER_COMPOSE }} up --detach --force-recreate --remove-orphans"

  install:
    - sh -c "mkdir freescout/vendor/natxet/cssmin/src"
    - sh -c "cp templates/.env.example freescout/.env"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan key:generate"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan migrate:fresh"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan storage:link"

  install-modules:
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan freescout:module-install itkprometheus"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan freescout:module-install itkissuecreate"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan freescout:module-install itkportalsubmit"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan freescout:module-install itkconversationchanges"

  fetch-modules:
    - git clone https://github.com/itk-dev/freescout-itk-issue-create.git {{ .PLUGIN_TARGET_DIR }}/ItkIssueCreate
    - git clone https://github.com/itk-dev/freescout-itk-portal-submit.git {{ .PLUGIN_TARGET_DIR }}/ItkPortalSubmit
    - git clone https://github.com/itk-dev/freescout-itk-conversation-changes.git {{ .PLUGIN_TARGET_DIR }}/ItkConversationChanges
    - task fetch-build-prometheus-module
    - sh -c "{{ .DOCKER_COMPOSE }} composer dumpautoload"
    - sh -c "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan freescout:clear-cache"

  fetch-build-prometheus-module:
    - git clone https://github.com/itk-dev/freescout-itk-prometheus.git {{ .PLUGIN_TARGET_DIR }}/ItkPrometheus
    - sh -c "{{ .DOCKER_COMPOSE }} composer install --working-dir=/app/Modules/ItkPrometheus"

  build-from-scratch:
    - task dist:build
    - task start-docker
    - task install
    - task fetch-modules
    - task install-modules

  artisan:
    desc: "Run artisan command, e.g. `task {{.TASK}} -- cache:clear`"
    cmds:
      - "{{ .DOCKER_COMPOSE }} exec phpfpm php artisan {{.CLI_ARGS}}"

  development:options-reset:
    prompt: "Really reset options?"
    cmds:
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db <<< \"UPDATE options SET value = 'mail' WHERE name='mail_host'\""
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db <<< \"UPDATE options SET value = '1025' WHERE name='mail_port'\""
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db <<< \"UPDATE options SET value = 'mail@freescout.local.itkdev.dk' WHERE name='mail_from'\""
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db <<< \"UPDATE options SET value = 'mail@freescout.local.itkdev.dk' WHERE name='send_test_to'\""
      # Promote all users
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db <<< \"UPDATE users SET role = 2\""

      - task artisan -- cache:clear
      - task artisan -- freescout:logout-users
      - rm -f freescout/storage/framework/sessions/* freescout/bootstrap/cache/*.*
      - task artisan -- freescout:clear-cache

  development:freescout-patch:
    prompt: "Really patch Freescout?"
    cmds:
      # - patch --strip=1 --dry-run < patches/freescout.patch && patch --strip=1 < patches/freescout.patch
      - patch --strip=1 --quiet < patches/freescout.patch
      - task artisan -- cache:clear

      # git add -f freescout/app/Misc/WpApi.php freescout/app/Module.php
      # git diff freescout > patches/freescout.patch

  # https://github.com/freescout-help-desk/freescout/wiki/Translate
  development:show-danish-translations:
    cmds:
      - "{{ .DOCKER_COMPOSE }} exec --no-TTY mariadb mysql --user=db --password=db db --table <<< \"SELECT * FROM ltm_translations WHERE locale = 'da' AND value IS NOT NULL;\""

  development:pull:
    prompt: This will override your files. Continue?
    cmds:
      - rsync -azv ${REMOTE_HOST}:${REMOTE_FREESCOUT_PATH} --exclude cache --exclude sessions --exclude logs --exclude builds .
      # Make sure that folders not rsync'ed exist
      - mkdir -p freescout/bootstrap/cache freescout/storage/logs freescout/storage/framework/{cache,sessions} freescout/public/js/builds
      - rm -fr freescout/bootstrap/cache/* freescout/storage/logs/* freescout/storage/framework/{cache,sessions}/* freescout/public/js/builds/*
      # Apparently, first one wins, so we set some variables first in the env file.
      - |
          (
          echo "# Local development"
          echo APP_URL=https://freescout.local.itkdev.dk
          echo APP_DEBUG=true
          echo DB_HOST=mariadb
          echo DB_DATABASE=db
          echo DB_USERNAME=db
          echo DB_PASSWORD=db

          cat freescout/.env
          ) > freescout/.env.tmp
          mv freescout/.env.tmp freescout/.env
      - task artisan -- cache:clear
      - task artisan -- freescout:build
      - task: development:freescout-patch
      - task: development:options-reset
      - docker compose up --detach --force-recreate
    # https://taskfile.dev/reference/schema/#requires
    requires:
      vars:
        - REMOTE_HOST
        - REMOTE_FREESCOUT_PATH
