version: '3'

dotenv: [".task.env"]

vars:
  TARGET_DIR: 'freescout'
  PLUGIN_TARGET_DIR: 'freescout/Modules'
  DOCKERCMD: 'itkdev-docker-compose'
  DOCKERCMD_SERVER: 'itkdev-docker-compose-server'

tasks:
  dist:build:
    summary: Install Freescout distribution
    cmds:
      - sh -c "wget https://github.com/freescout-help-desk/freescout/archive/refs/tags/{{.VERSION}}.tar.gz"
      - sh -c "mkdir freescout"
      - sh -c "tar -xzf ./{{.VERSION}}.tar.gz --strip-components 1 -C freescout"
      - sh -c "rm {{.VERSION}}.tar.gz"

  fetch-modules:
    - git clone https://github.com/itk-dev/freescout-itk-issue-create.git {{ .PLUGIN_TARGET_DIR }}/ItkIssueCreate
    - git clone https://github.com/itk-dev/freescout-itk-portal-submit.git {{ .PLUGIN_TARGET_DIR }}/ItkPortalSubmit
    - git clone https://github.com/itk-dev/freescout-itk-conversation-changes.git {{ .PLUGIN_TARGET_DIR }}/ItkConversationChanges
    - task install-prometheus-module

  dev:start-docker:
    cmds:
      - sh -c "{{ .DOCKERCMD }} up --detach --force-recreate --remove-orphans"

  dev:install:
    - sh -c "cp templates/.env.example freescout/.env"
    - sh -c "{{ .DOCKERCMD }} exec phpfpm php artisan key:generate"
    - sh -c "{{ .DOCKERCMD }} exec phpfpm php artisan migrate:fresh"

  dev:install-modules:
    - task fetch-modules
    - sh -c "{{ .DOCKERCMD }} exec phpfpm php artisan freescout:clear-cache"
    - sh -c "{{ .DOCKERCMD }} composer dumpautoload"

  server:start-docker:
    cmds:
      - sh -c "{{ .DOCKERCMD_SERVER }} up --detach --force-recreate --remove-orphans"

  server:install:
    - sh -c "mkdir freescout/vendor/natxet/cssmin/src"
    - sh -c "cp templates/.env.example freescout/.env"
    - sh -c "{{ .DOCKERCMD_SERVER }} exec phpfpm php artisan key:generate"
    - sh -c "{{ .DOCKERCMD_SERVER }} exec phpfpm php artisan migrate:fresh"

  server:install-modules:
    - task fetch-modules
    - sh -c "{{ .DOCKERCMD_SERVER }} exec phpfpm php artisan freescout:clear-cache"
    - sh -c "{{ .DOCKERCMD_SERVER }} exec phpfpm composer dumpautoload"

  install-prometheus-module:
    - git clone https://github.com/itk-dev/freescout-itk-prometheus.git {{ .PLUGIN_TARGET_DIR }}/ItkPrometheus
    - sh -c "{{ .DOCKERCMD }} composer install --working-dir=/app/Modules/ItkPrometheus"
