version: '3'

dotenv: [".task.env"]

vars:
  TARGET_DIR: 'freescout'
  PLUGIN_TARGET_DIR: 'freescout/Modules'
  DOCKERCMD: 'itkdev-docker-compose'
  DOCKERCMD_SERVER: 'itkdev-docker-compose-server'

tasks:
  dist:clone:
    summary: Clone freescout distribution.
    cmds:
      - git clone https://github.com/freescout-help-desk/freescout {{ .TARGET_DIR }}

  dev:start-docker:
    cmds:
      - sh -c "{{ .DOCKERCMD }} up --detach --force-recreate --remove-orphans"

  server:start-docker:
    cmds:
      - sh -c "{{ .DOCKERCMD_SERVER }} up --detach --force-recreate --remove-orphans"

  dev:install:sample-module:
    summary: Clones sample module into modules folder.
    cmds:
      - git clone https://github.com/freescout-help-desk/SampleModule {{ .PLUGIN_TARGET_DIR }}/SampleModule
      - sh -c "{{ .DOCKERCMD }} exec phpfpm php artisan freescout:clear-cache"
